name: prediction-service
channels:
  - defaults
dependencies:
  - gunicorn=19.8.*
  - jupyter=1.0.*
  - pillow=5.1.*
  - pip=10.0.*
  - pytest=3.6.*
  - python=3.6.*
  - ujson=1.35
  - pip:
    - absl-py==0.2.2
    - astor==0.7.1
    - cython==0.28.4
    - falcon==1.4.1
    - gast==0.2.0
    - grpcio==1.13.0
    - gevent==1.3.4
    - h5py==2.8.0
    - locustio==0.8.1
    - keras==2.2.0
    - keras-applications==1.0.2
    - keras-preprocessing==1.0.1
    - markdown==2.6.11
    - powerline-status==2.6
    - protobuf==3.6.0
    - python-mimeparse==1.6.0
    - pyyaml==3.13
    - scipy==1.1.0
    - tensorboard==1.8.0
    - tensorflow==1.8.0
    - termcolor==1.1.0
    - werkzeug==0.14.1
